### ISSUE TITLE
#bug OnReady Attribute can't contain any parameter

### ISSUE THREAD

**Issue by MadFlyFish** [31/GodotOnReady#41]
![image](https://user-images.githubusercontent.com/36298330/167373791-607c8716-0224-4f59-8d1e-8189c56fd247.png)
![image](https://user-images.githubusercontent.com/36298330/167374111-c895ce20-1657-42c3-9cc6-3d77a9ca5680.png)

Thanks

**Comment by 31** [comment]
This is intentional: `Order` must be assigned by name, like `[OnReady(Order = 2)]`. I figure that it should be extremely rare to actually have to use `Order`, so when you do, it's ok to have the name there. It also helps clarify what the `2` means, and means I can add more arguments to `OnReady` in the future without dealing with the order of existing nameless arguments.

(I expect `path` in `[OnReadyGet("...")]` to be extremely commonly used, and that's why it's accepted as a nameless arg.)

Do you think it should be accepted without the name? (Are you using `Order` often?)

**Comment by MadFlyFish** [comment]
I'm ok with it.  Thanks
Run into this problem when testing every function mentioned in document.
I guess  Order is rare to used in my case

**Comment by 31** [comment]
Ah, cool. I'll add an example to the readme to make it a little clearer. (Intellisense/autocomplete in your editor *should* have helped with suggesting the right syntax, but I might as well make the project readme clearer by itself.) Thanks for pointing this out.

**Comment by 31** [comment]
Ok, got an example in, and rewrote some of the text in the section to hopefully make it a little clearer in other ways too. 😄 https://github.com/31/GodotOnReady#onready-1

Thanks again!
