### ISSUE TITLE
Error when get a property of a node

### ISSUE THREAD

**Issue by MadFlyFish** [31/GodotOnReady#42]
![image](https://user-images.githubusercontent.com/36298330/167378153-239c93c3-b570-42c6-b069-0e8d0164d08e.png)

![image](https://user-images.githubusercontent.com/36298330/167377981-cb1ec6b2-3129-4943-9433-802527433a23.png)

![image](https://user-images.githubusercontent.com/36298330/167378284-68f43c47-8727-41e9-9e41-0b6fa38bc3c8.png)

![image](https://user-images.githubusercontent.com/36298330/167377945-510ff890-743a-4754-9640-22b497db4e16.png)

**Comment by MadFlyFish** [comment]
It seems that it is treated as a resource rather than a node

**Comment by 31** [comment]
Hmm. I probably broke this with some recent changes to accommodate some unusual situations. You could try 1.1.6 until I can fix it.

**Comment by MadFlyFish** [comment]
Well, 1.1.6 works fine on this issue. Thanks.
And by the way, I think OnReadyFind is unnecessary, because godot 3.5 beta5 has Implemented the function of scene unique nodes ,which is more reasonable.
https://github.com/godotengine/godot/pull/60527
![image](https://user-images.githubusercontent.com/36298330/167454193-541f809d-f8f4-48b3-a7ee-c7a8d613d0ec.png)

**Comment by 31** [comment]
Once "scene unique nodes" (which does looks nice) is in a stable release, it does seem to overlap what OnReadyFind can do, although not quite all. It would also require changing code to start using it, and I don't see the reason to force people to do that by removing OnReadyFind.

I'm just waiting to see if GodotOnReady is necessary in 4.0 and either rewrite to fit or drop it entirely. 😄 GodotOnReady as a whole *should* be obsolete in 4.0, since this issue's milestone is set:

* https://github.com/godotengine/godot-proposals/issues/2425

**Comment by MadFlyFish** [comment]
Thanks for the details. 
I think 4.0 stable  will face a long wait and I will stick to 3.x in my case.
GodotOnReady is still a great addition to 3.x and keeps code clean.

**Comment by 31** [comment]
I've fixed this up and released GodotOnReady 1.2.1. (But, OnReadyFind is the only thing that's been added since 1.1.6, so no need to upgrade if you aren't planning on using it. 😄.)

Thanks for noticing and filing the issue!

**Comment by MadFlyFish** [comment]
1.2.1 works fine.
