### ISSUE TITLE
OnReadyFindParent - Injecting dependencies dynamically when new scenes get created

### ISSUE THREAD

**Issue by DasOhmoff** [31/GodotOnReady#45]
Hey :wave:, thank you for this awesome plugin.

One of the nice feature of using `[OnReadyGet]` is that it allows dependency inversion. Making the code a lot more cleaner and way more maintainable.

Right now I have the following issue: If a scene was not created yet, it cannot have NodePaths applied to its parents objects, as it was not added as a child yet. This makes it awkward to inject dependencies into scenes, because no node paths can be set. To solve this, I am using `FindParent("...")` in the child scenes, so that it can then use the parents public interface to access the required dependencies. Example:
```
    public override void _Ready()
    {
        Arena arena = (Arena)FindParent("Arena");
        eventHub = arena.EventHub;
        playersInfo = arena.PlayersInfo;
    }
```

It would be great if there was something like `OnReadyFindParent("...")` that could automatically inject the required dependencies on startup. Example:
```
//Good
[OnReadyFindParent("Arena")]
private Arena arena;

//Better
[OnReadyFindParent("Arena", Property = "EventHub")]
private EventHub eventHub;

//Best
[OnReadyFindParent("Arena", Property = typeof(EventHub))]
private EventHub eventHub;
```

This feature would be greatly appriciated!

**Comment by 31** [comment]
Hi, thanks for the suggestion! I don't have a problem with adding something like this, but I'm not sure what behavior you're proposing with `//Best`:

> ```cs
> //Better
> [OnReadyFindParent("Arena", Property = "EventHub")]
> private EventHub eventHub;
> 
> //Best
> [OnReadyFindParent("Arena", Property = typeof(EventHub))]
> private EventHub eventHub;
> ```

Does passing a type mean that it should find any property with that type? Or would `nameof` be a better fit here? (In which case `Better` would behave the same?)

---

I'm not a big fan of the use case, for what it's worth. 😅 I don't think I would call this dependency injection:

> ```cs
>     public override void _Ready()
>     {
>         Arena arena = (Arena)FindParent("Arena");
>         eventHub = arena.EventHub;
>         playersInfo = arena.PlayersInfo;
>     }
> ```

Depending on the context, it seems to me to go against this practice in Godot:

> **If at all possible, one should design scenes to have no dependencies.** That is, one should create scenes that keep everything they need within themselves.
>
> (https://docs.godotengine.org/en/stable/tutorials/best_practices/scene_organization.html#how-to-build-relationships-effectively)

For dependency injection, I would expect the parent node to pass values down into its children, rather than the children depending on specific ancestor nodes being present somewhere up the tree.

Grabbing data from ancestor nodes in `_Ready` also needs to be done with care, because the ancestors most likely aren't Ready themselves yet.

If this is only being done within a scene, not cascading into ancestor scenes, perhaps a Scene Unique Node could be used instead? ([New in Godot 3.5+](https://godotengine.org/article/release-candidate-godot-3-5-rc-4).)

If you're aware of all this and the approach simply works well for you anyway, that's perfectly fine by me, but figured it's worth mentioning. I don't want to end up encouraging that people use it this way if they don't know what they're getting into. 😄

**Comment by 31** [comment]
> One creates any dynamic amount of arenas, and then places new objects into the arenas on demand. The new objects need to know in which arena they were placed in. I don't know of any way to include this information within the objects scenes. I am happy to be wrong here, if there is somehow a way to do so.

My answer to this one (I've heard something just like it before in Discord chat 😄) is that the arena should be in control of its children/descendants. Does a node outside the arena (or inside the arena, for that matter) want to put a new node into the arena? It has to tell the arena to do it. Then, the arena has the opportunity to inject itself into the node before adding it to the tree.

> Also, when injecting, in order to inject the dependencies or call the initialization method, the parent would always need to know the type of the child that is being injected, not allowing dynamic creation of any type of children.

You can have the hypothetical node-adding method in Arena use `if (foo is Bar b) { b.Arena = this; }` to let it handle very broad node types while also doing special injection for specific subtypes.

You can also go one step further and use `interface`s to define the injectable properties, which decouples it a little further. Then, nodes can pick and choose which interfaces/properties it wants to have injected by implementing various interfaces, while the Arena doesn't care at all about specific types of node.

---

That all said, even if this idealistic way *works*, it might end up being more cumbersome, and I'm still definitely ok adding this feature to make the lookup-parent-in-`_Ready` easier without overhauling the general approach. I would add a new attribute and generator code to make these all work (which should do the same thing):

```cs
[OnReadyFindParent("Arena", Property = "EventHub")] private EventHub eventHub;
[OnReadyFindParent("Arena", Property = nameof(EventHub))] private EventHub eventHub;
[OnReadyFindParent("Arena", Property = nameof(Arena.EventHub))] private EventHub eventHub;
// ^ This one just makes sure that if you rename the *property* rather than the *class*, the refactoring action finds this usage.
```

Let me know if you'd still find this useful. 🙂

**Comment by DasOhmoff** [comment]
> It has to tell the arena to do it. Then, the arena has the opportunity to inject itself into the node before adding it to the tree.

I was responding here to "If at all possible, one should design scenes to have no dependencies.". My point was that it is not possible here. The newly placed objects has the arena as its dependency.

> use `if (foo is Bar b) { b.Arena = this; }`
> use interfaces to define the injectable properties

This is probably still the best idea so far, and I thought of that as well. My problem with this is that it breaks the open closed principle. Adding some injectable property would require to alter the `Arena` class. Maybe this somehow could be fixed with some automatic self registration when new injectable property classes get added or so.

> Let me know if you'd still find this useful

I think that is pretty good. Thanks. Just to be clear, `nameof(EventHub)` refers to the type of the property, and not its name, correct?

**Comment by 31** [comment]
> I was responding here to "If at all possible, one should design scenes to have no dependencies.". My point was that it is not possible here. The newly placed objects has the arena as its dependency.

That's true. I guess because the next paragraph goes into dependency injection, I mashed it up and treated the whole doc as saying the same thing, which it's not. My point is really just that it makes more sense to me for the parent to be responsible for injecting the values rather than the subscene trying to look them up based on assumptions about the scene that contains it and (potentially) its `_Ready` status. Dependency being provided (perhaps even optionally) vs. "hard" dependency on a particular ancestor node arrangement.

> > use `if (foo is Bar b) { b.Arena = this; }`
> > use interfaces to define the injectable properties
> 
> This is probably the best idea so far, and I thought of that as well. My problem with this is that it breaks the open closed principle. For example adding some injectable property interface would require to alter the `Arena` class. Maybe this somehow could be fixed with some automatic self registration when new injectable property interfaces get added or so.

I don't understand the mapping of this principle onto this situation. But yeah, if it helps the overall architecture, it seems like a pretty easy way to avoid modifying `Arena` would be to have a list of injectors that are applied to each new object rather than having the injection code itself in an `Arena` method. It seems like it'd be wasted effort if `Arena` is the only thing doing injecting, though.

> Just to be clear, `nameof(EventHub)` refers to the type of the property, and not its name, correct?

This is a bit confusing to talk about because the property has the same name as the type. (This way of naming properties is definitely idiomatic in C#, it just makes it harder to be specific when talking about it. 😛)

Let's call it `public EventHub HotdogEventHub { get; set; }` for now. Generally speaking, `nameof(EventHub)` refers to whatever the identifier `EventHub` means in that context. In the context of the child class:

* For `nameof(EventHub)`, if there's a property `public Something EventHub { get; set; }` or field, etc. in the child class, it refers to that.
* If not, `nameof(EventHub)` refers to the `EventHub` class.
* `nameof(HotdogEventHub)` would result in `cs0103` because that name doesn't mean anything in this context.
* `nameof(Arena.HotdogEventHub)` refers to the property.

It evaluates at compile time to the name of the identifier, so either `EventHub` or `HotdogEventHub` for those cases.

**Comment by DasOhmoff** [comment]
> My point is really just that it makes more sense to me for the parent to be responsible for injecting the values rather than ...

> it seems like a pretty easy way to avoid modifying Arena would be to have a list of injectors that ...

Yes, I think so too.

About the EventHub and HotdogEventHub: Now I understand, and I like it, just one more question about:

> If not, nameof(EventHub) refers to the EventHub class.

Because it refers to the type of the class, will it also, or could it also be nicely possible to, find a property of this type? For example:
```cs
//In the Arena class (parent):
public EventHub EventHubHotdog;    // <- implements the IEventHub interface

//In the child class:
[OnReadyFindParent("Arena", Property = typeof(IEventHub))]    // <- notice that its an interface type (not a name of a field or so)
private IEventHub eventHubHotdog;
```

**Comment by 31** [comment]
> Because this refers to a type and not a string (by using `nameof`), will it also, or could it also be nicely possible to, find a property of a certain type, instead of finding through the property and field names?

Yeah, but first, another ambiguity to take care of. 😄 Let's call the node's name `Colosseum`, and the script/class attached to it `Arena`.

A semi-missing piece here is the actual type of the ancestor node. With this attribute+field:

```cs
[OnReadyFindParent("Colosseum", Property = typeof(IEventHub))] private IEventHub eventHubHotdog;
```

The ancestor's class, `Arena`, is nowhere to be found. With the opposite:

```cs
[OnReadyFindParent(typeof(Arena), Property = typeof(IEventHub))] private IEventHub eventHubHotdog;
```

Then the ancestor's node name is nowhere to be found.

The node name is more important, since the generated code needs to pass it to `FindParent`. From there, even without the class name, the generator *could* use `GetPropertyList` and `Get` each property until it finds a value with the right type. Something interesting about this is that it would also work with GDScript or C# scripts equally. (But I don't think this is all that valuable, since we're working in C# already, and the perf hit would be unfortunate.)

To be efficient and call `eventHubHotdog = [...FindParent...].EventHub` directly, we need both. Luckily `Property = typeof(IEventHub)` is not necessary because `IEventHub` is already the type of the field, so we can drop that while adding the remaining info to avoid making the line any longer:

```cs
[OnReadyFindParent(typeof(Arena), "Colosseum")] private IEventHub eventHubHotdog;
```

I'm not happy calling this `OnReadyFindParent` because it's specialized way beyond the other attributes in the library, and doesn't match what I'd expect that attribute name to do in the context of the other attribute names. I'd probably cut to the chase with a name more like this:

```cs
[InjectAncestorValue(typeof(Arena), "Colosseum")] private IEventHub eventHubHotdog;
```

(`OnReadyFindParentMemberSingleTypeMatchValue` or something like that came to mind first, but I think going with a scenario-based name rather than behavior is clearer here. 😄)

I think giving the second parameter a default that assumes the node name == the type name is also reasonable, since this is a common convention in Godot (IMO). So if we go back to calling both the node name `Arena` and the class `Arena`:

```cs
[InjectAncestorValue(typeof(Arena))] private IEventHub eventHubHotdog;
```

Coding with that naming convention in mind might have been what you were thinking in the first place, but maybe it was worth writing down the full thought process anyway. 🙂

A few more details:

* I think the generator should look for exactly one field/property in the target class that matches the field/property type. If there is no match, or more than one match, it would emit a compile error on the `InjectAncestorValue` line.
* If a field/property has a more concrete type than the requested type, it's a match. E.g. `TallEventHub` would satisfy `IEventHub`.

Sound reasonable?

**Comment by DasOhmoff** [comment]
Yes. That sound great 👌 . Very nice :)

**Comment by 31** [comment]
Do you have GodotOnReady setup so you can try out this PR? (Or are you just using it from the NuGet package?) Let me know if you can give it a try and confirm it works in your specific situation, or I'll go ahead and merge and make a new package version:

* https://github.com/31/GodotOnReady/pull/46

**Comment by 31** [comment]
Ok, no problem. I've pushed 1.2.2 with the change and it's going through the gallery's validation process now.
